---
name: vscode-java-debug-17
description: The debug server implementation for Java. It conforms to the debugger adapter protocol.
homepage: https://github.com/microsoft/java-debug
licenses:
  - EPL-1.0
languages:
  - Java
categories:
  - DAP

source:
  id: pkg:openvsx/vscjava/vscode-java-debug@0.58.2
  download:
    file: vscjava.vscode-java-debug-{{version}}.vsix

share:
  vscode-java-debug/: extension/server/
  vscode-java-debug/com.microsoft.java.debug.plugin.jar: extension/server/com.microsoft.java.debug.plugin-0.53.2.jar
